var areas = [
  {
    url: "http://havas.az",
    title: "Havas Azerbaijan",
    start: [47, 9],
    end: [53, 15],
    alt: "alt",
  },
  {
    url: "https://www.instagram.com/tapmacam",
    title: "Tapmaca Academy | Çox bilmək balacalara xoş gələcək",
    start: [16, 10],
    end: [22, 16],
    alt: "alt",
  },
  {
    url: "https://3sual.az",
    title: "3sual.az | İntellektual Oyunlar üçün platforma",
    start: [30, 4],
    end: [35, 8],
    alt: "alt",
  },
  {
    url: "https://corabb.az",
    title: "Corabb | Azərbaycanın yerli corab markası",
    start: [80, 7],
    end: [88, 10],
    alt: "alt",
  },
  {
    url: "https://www.instagram.com/anar.mirzazadeh",
    title: "Anar Mirzazadeh | Visual Artist | Creative Director | Astronaut",
    start: [58, 37],
    end: [61, 40],
    alt: "alt",
  },
  {
    url: "https://www.instagram.com/pakdent",
    title: "Pak Dent | Müasir stomatoloji klinika",
    start: [8, 32],
    end: [10, 34],
    alt: "alt",
  },
  {
    url: "https://sahliyali.com/halal-nem%C9%99t-1000-b%C9%99r%C9%99k%C9%99t",
    title: "Halal Nemət, 1000 Bərəkət",
    start: [63, 21],
    end: [66, 24],
    alt: "alt",
  },
  {
    url: "",
    title: "Anonim xeyriyyəçi | E.Q.",
    start: [1, 94],
    end: [8, 101],
    alt: "alt",
  },
  {
    url: "https://www.instagram.com/bluebake.az",
    title: "BlueBake | Diabetik, şəkərsiz və qlütensiz şirniyyatlar 😋",
    start: [57, 5],
    end: [60, 8],
    alt: "alt",
  },
  {
    url: "https://www.instagram.com/fuzzyquiz",
    title: "Fuzzy | İntellektual asudə vaxt artıq bir trenddir!",
    start: [32, 25],
    end: [38, 26],
    alt: "alt",
  },
  {
    url: "https://www.instagram.com/shabnam.abdullaa",
    title: "Shabnam Abdulla | Part-time Traveler & Visual storyteller",
    start: [85, 29],
    end: [86, 30],
    alt: "alt",
  },
  {
    url: "site11.com",
    title: "site11",
    start: [20, 1],
    end: [22, 3],
    alt: "alt",
  },
  {
    url: "site12.com",
    title: "site12",
    start: [1, 7],
    end: [2, 9],
    alt: "alt",
  },
  {
    url: "site13.com",
    title: "site13",
    start: [1, 3],
    end: [2, 4],
    alt: "alt",
  },
  {
    url: "site14.com",
    title: "site14",
    start: [1, 4],
    end: [2, 5],
    alt: "alt",
  },
  {
    url: "site14.com",
    title: "site14",
    start: [1, 5],
    end: [4, 6],
    alt: "alt",
  },
  {
    url: "site15.com",
    title: "site15",
    start: [1, 6],
    end: [2, 7],
    alt: "alt",
  },
  {
    url: "site16.com",
    title: "site16",
    start: [1, 7],
    end: [4, 10],
    alt: "alt",
  },
  {
    url: "site17.com",
    title: "site17",
    start: [1, 10],
    end: [3, 12],
    alt: "alt",
  },
  {
    url: "site18.com",
    title: "site18",
    start: [1, 12],
    end: [2, 13],
    alt: "alt",
  },
  {
    url: "site19.com",
    title: "site19",
    start: [1, 13],
    end: [2, 14],
    alt: "alt",
  },
  {
    url: "site20.com",
    title: "site20",
    start: [1, 14],
    end: [2, 15],
    alt: "alt",
  },
  {
    url: "site21.com",
    title: "site21",
    start: [1, 15],
    end: [4, 16],
    alt: "alt",
  },
  {
    url: "site22.com",
    title: "site22",
    start: [1, 16],
    end: [2, 17],
    alt: "alt",
  },
  {
    url: "site23.com",
    title: "site23",
    start: [1, 17],
    end: [2, 18],
    alt: "alt",
  },
  {
    url: "site24.com",
    title: "site24",
    start: [1, 18],
    end: [2, 20],
    alt: "alt",
  },
  {
    url: "site25.com",
    title: "site25",
    start: [1, 19],
    end: [2, 20],
    alt: "alt",
  },
  {
    url: "site7.com",
    title: "site7",
    start: [15, 1],
    end: [16, 2],
    alt: "alt",
  },
  {
    url: "site26.com",
    title: "site26",
    start: [1, 20],
    end: [4, 21],
    alt: "alt",
  },
  {
    url: "site27.com",
    title: "site27",
    start: [1, 21],
    end: [10, 27],
    alt: "alt",
  },
];
